# Documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/OSLC4Net_SDK" # Location of package manifests
    open-pull-requests-limit: 12
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

  - package-ecosystem: nuget
    directory: /OSLC4Net_NETFramework/OSLC4Net.Client.Jazz
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /OSLC4Net_NETFramework/OSLC4Net.Client.Samples
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /OSLC4Net_NETFramework/OSLC4Net.StockQuoteSample
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /OSLC4Net_SDK/Examples/Oslc4NetExamples.Client
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /OSLC4Net_SDK/OSLC4Net.ChangeManagement
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /OSLC4Net_SDK/OSLC4Net.Client
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /OSLC4Net_SDK/OSLC4Net.Core.DotNetRdfProvider
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /OSLC4Net_SDK/OSLC4Net.Core.JsonProvider
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /OSLC4Net_SDK/OSLC4Net.Core.Query
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /OSLC4Net_SDK/OSLC4Net.Core
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /OSLC4Net_SDK/Tests/OSLC4Net.ChangeManagementTest
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /OSLC4Net_SDK/Tests/OSLC4Net.Client.Tests
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /OSLC4Net_SDK/Tests/OSLC4Net.Core.DotNetRdfProviderTests
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /OSLC4Net_SDK/Tests/OSLC4Net.Core.JsonProviderTests
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /OSLC4Net_SDK/Tests/OSLC4Net.Core.QueryTests
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /OSLC4Net_SDK/Tests/OSLC4Net.Core.QueryTests/data
    schedule:
      interval: daily
